MyPortfolio/Controllers/AdministrationController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration;

    [Authorize(Roles = Admin)]
    [Authorize(Policy = WritePolicy)]
    public class AdministrationController : Controller
    {
        private readonly IAdministrationService administration;

        public AdministrationController(IAdministrationService administration) => this.administration = administration; 

        [HttpGet] 
        public IActionResult Create()
        {
            var model = this.administration.PrepareForCreateRole();

            return this.View(model);
        }
        
        [HttpPost] 
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.administration.CrateRoleAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Succesfully added role!"
            });

            return RedirectToAction("Index", "Home"); 
        } 

        public async Task<IActionResult> GetAdmins()
        {
            var model = await this.administration.GetAllAdminsAsync();

            return this.View(model); 
        }

        public async Task<IActionResult> AdministrationUsers() 
        {
            var model = await this.administration.GetAllUsersAsync();

            return this.View(model);   
        }

        public async Task<IActionResult> Ban(string id)
        {
            await this.administration.BanAsync(id); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Danger,
                Message = "This account is LockOut!"
            }); 

            return RedirectToAction("Users"); 
        } 

        public async Task<IActionResult> UnBan(string id)
        {
            await this.administration.UnBanAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Тhis account is unlocked!"
            });

            return RedirectToAction("Users"); 
        } 
    }
}

MyPortfolio/Controllers/CourseController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using MyPortfolio.ViewModels.EditViewModel;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class CourseController : Controller
    {
        private readonly ICourseService course;

        public CourseController(ICourseService course) => this.course = course;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddCourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.course.AddCourseAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The course is added successfully!"   
            });

            return RedirectToAction("Index");  
        } 

        public async Task<IActionResult> Index() 
        {
            var model = await this.course.GetAllCoursesAsync();

            return View(model); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.course.PrepareForEditingAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditCourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.course.EditAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The course is edited successfully!"
            });

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)] 
        public async Task<IActionResult> Remove(int id)
        {
            await this.course.RemoveAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The course is deleted successsfully!" 
            });

            return RedirectToAction("Index"); 
        }
    }
}

MyPortfolio/Controllers/HobieController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class HobieController : Controller
    {
        private readonly IHobieService hobie; 

        public HobieController(IHobieService hobie) => this.hobie = hobie;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddHobieViewModel model) 
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.hobie.AddAsync(model); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfully added!"
            }); 

            return RedirectToAction("Index"); 
        } 

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await this.hobie.GetAllHobiesAsync();

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)] 
        public async Task<IActionResult> Remove(int id)
        {
            await this.hobie.RemoveAsync(id); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The hobie is removed!"
            }); 

            return RedirectToAction("Index"); 
        }
    }
}

MyPortfolio/Controllers/MessageController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Infrastructure.Services;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class MessageController : Controller
    {
        private readonly IMessageService message;
        private readonly ICurrentUserService currentUser; 

        public MessageController(
            IMessageService message,
            ICurrentUserService currentUser)
        {
            this.message = message;
            this.currentUser = currentUser;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create() 
        {
            var username = this.currentUser.GetUsername();

            var model = new CreateMessageViewModel
            {
                Username = username,
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateMessageViewModel model)  
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.message.CreateAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Your message was sent successfully. We will contact you!"
            });

            return RedirectToAction("Index", "Home"); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Messages() 
        {
            var model = await this.message.MessagesAsync();

            return this.View(model); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Details(int id)
        {
            var model = await this.message.DetaislsAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Clear(int id)
        {
            await this.message.ClearAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfull!"
            });

            return RedirectToAction("Messages");  
        }
    }
}

MyPortfolio/Controllers/SkillController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using MyPortfolio.ViewModels.EditViewModel;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class SkillController : Controller
    {
        private readonly ISkillService skill;

        public SkillController(ISkillService skill) => this.skill = skill;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddSkillViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();  
            } 

            await this.skill.AddAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Succesfully added!" 
            });

            return RedirectToAction("Index", "Home");  
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.skill.PrepareForEditingAsync(id); 

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditSkillViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.skill.EditAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "This skill is edited!"
            });

            return RedirectToAction("Index", "Home");
        } 

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Remove(int id)
        {
            await this.skill.RemoveAsync(id); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "This skill is removed successfully!" 
            }); 

            return RedirectToAction("Index", "Home");  
        }
    }
}

MyPortfolio/Views/Administration/AdministrationUsers.cshtml
@model IEnumerable<MyPortfolio.ViewModels.AdministrationVIewModel.UsersViewModel>

@{
    ViewData["Title"] = "Administration";
}
<br />
<a asp-controller="Course" asp-action="Add" class="w3-button w3-button-group w3-light-grey w3-padding-large">Add Course</a>
<a asp-controller="Education" asp-action="Add" class="w3-button w3-button-group w3-light-grey w3-padding-large">Add Education</a>
<a asp-controller="Skill" asp-action="Add" class="w3-button w3-button-group w3-light-grey w3-padding-large">Add Skill</a>
<a asp-controller="Hobie" asp-action="Add" class="w3-button w3-button-group w3-light-grey w3-padding-large">Add Hobie</a>
<br />
<br />
<a asp-controller="Project" asp-action="Add" class="w3-button w3-light-grey w3-padding-large">Add Project</a>
<a asp-controller="Experience" asp-action="Add" class="w3-button w3-button-group w3-light-grey w3-padding-large">Add Experience</a>
<a asp-controller="Administration" asp-action="GetAdmins" class="w3-button w3-light-grey w3-padding-large">Admins</a> 
<a asp-controller="Message" asp-action="Messages" class="w3-button w3-button-group w3-light-grey w3-padding-large">Messages</a> 
<br />
<br />

<head>
    <style>
        * {
            box-sizing: border-box;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

            #myTable th, #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: white;
                }

        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-image: url('searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

            input[type=text]:focus {
                width: 100%;
            }
    </style>
</head>
<body>

    <h2><b>Users</b></h2>
    <form>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for usernames..." title="Type in a name">
    </form>
    <table id="myTable">
        <tr class="header">
            <th style="width:60%;">Username</th>
            <th style="width:40%;">Email</th>
            <th style="width:40%;">Email Confirmed</th>
            <th style="width:40%;">Role</th>
            <th style="width:40%;">Locked</th>
            <th style="width:40%;">Ban</th>
            <th style="width:40%;">UnBan</th>
        </tr>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Email</td>
                <td>@user.EmailConfirmed</td>
                <td>@user.Role</td>
                <td>@user.IsLocked</td>
                @if (User.IsInRole("Admin"))
                {
                    <td><a asp-route-id="@user.Id" asp-controller="Administration" asp-action="Ban" class="btn btn-danger" role="button">Ban</a></td>
                    <td><a asp-route-id="@user.Id" asp-controller="Administration" asp-action="UnBan" class="btn btn-danger" role="button">UnBan</a></td>
                }
            </tr>
        }
    </table>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</body>

MyPortfolio/Views/Administration/Create.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole

@{
    ViewData["Title"] = "Add Role";
}
<br />
<h1><b>@ViewData["Title"]</b></h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}  

MyPortfolio/Views/Administration/GetAdmins.cshtml
@model IEnumerable<MyPortfolio.ViewModels.AdministrationVIewModel.UsersViewModel>

@{
    ViewData["Title"] = "Admins";
}

<head>
    <style>
        * {
            box-sizing: border-box;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

            #myTable th, #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: white;
                }

        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-image: url('searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

            input[type=text]:focus {
                width: 100%;
            }
    </style>
</head>
<body>

    <h2><b>Admins</b></h2> 
    <form>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for usernames..." title="Type in a name">
    </form>
    <table id="myTable">
        <tr class="header">
            <th style="width:60%;">Username</th>
            <th style="width:40%;">Email</th>
            <th style="width:40%;">Email Confirmed</th>
            <th style="width:40%;">Role</th>
        </tr>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Email</td>
                <td>@user.EmailConfirmed</td>
                <td>@user.Role</td>
            </tr>
        }
    </table>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</body>