MyPortfolio/Controllers/ExperienceController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using MyPortfolio.ViewModels.EditViewModel;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class ExperienceController : Controller
    {
        private readonly IExperienceService experience;

        public ExperienceController(IExperienceService experience) => this.experience = experience;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost] 
        public async Task<IActionResult> Add(AddExperienceViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            }

            await this.experience.AddAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfully added!"
            }); 

            return RedirectToAction("Index"); 
        } 

        public async Task<IActionResult> Index() 
        {
            var model = await this.experience.ExperiencesAsync();

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.experience.PrepareForEditingAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditExperienceViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            await this.experience.EditAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The experience is edited!"
            });

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Remove(int id)
        {
            await this.experience.RemoveAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The experience is removed!"
            }); 

            return RedirectToAction("Index"); 
        }
    }
}

MyPortfolio/Views/Experience/Add.cshtml
@model MyPortfolio.ViewModels.BidingViewModels.AddExperienceViewModel

@{
    ViewData["Title"] = "Add";
}

<h1>Add <b>Experience</b></h1> 

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Responsibilities" class="control-label"></label>
                <input asp-for="Responsibilities" class="form-control" />
                <span asp-validation-for="Responsibilities" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyPortfolio/Views/Experience/Edit.cshtml
@model MyPortfolio.ViewModels.EditViewModel.EditExperienceViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData["Title"] <b>Experience</b></h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Responsibilities" class="control-label"></label>
                <input asp-for="Responsibilities" class="form-control" />
                <span asp-validation-for="Responsibilities" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyPortfolio/Views/Experience/Index.cshtml
@model IEnumerable<MyPortfolio.ViewModels.ExperienceViewModel.IndexExperienceViewModel>

    <style>
        html, body, h1, h2, h3, h4, h5, h6 {
            font-family: "Roboto", sans-serif
        }
    </style>

    <body>
            <div class="w3-container w3-card w3-white w3-margin-bottom">
                <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Professional <b>Experience</b></h2>
                <div class="w3-container">
                    @foreach (var experience in Model)
                    {
                        <h5 class="w3-opacity"><b>@experience.Name</b></h5>
                        <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>@experience.Start.Date - <span class="w3-tag w3-teal w3-round">@experience.End.Date</span></h6>
                        <p>@experience.Description</p>
                        <p><b>Responsibilities:</b> @experience.Responsibilities</p><br />

                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-route-id="@experience.Id" asp-controller="Experience" asp-action="Edit" class="btn btn-outline-dark"><b>Edit</b></a>
                            <a asp-route-id="@experience.Id" asp-controller="Experience" asp-action="Remove" class="btn btn-outline-dark"><b>Remove</b></a>
                        }
                        <hr>
                    }
                </div>
            </div>
    </body>