MyPortfolio/Controllers/CourseController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using MyPortfolio.ViewModels.EditViewModel;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class CourseController : Controller
    {
        private readonly ICourseService course;

        public CourseController(ICourseService course) => this.course = course;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddCourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.course.AddCourseAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The course is added successfully!"   
            });

            return RedirectToAction("Index");  
        } 

        public async Task<IActionResult> Index() 
        {
            var model = await this.course.GetAllCoursesAsync();

            return View(model); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.course.PrepareForEditingAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditCourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.course.EditAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The course is edited successfully!"
            });

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)] 
        public async Task<IActionResult> Remove(int id)
        {
            await this.course.RemoveAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The course is deleted successsfully!" 
            });

            return RedirectToAction("Index"); 
        }
    }
}

MyPortfolio/Controllers/HobieController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class HobieController : Controller
    {
        private readonly IHobieService hobie; 

        public HobieController(IHobieService hobie) => this.hobie = hobie;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddHobieViewModel model) 
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.hobie.AddAsync(model); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfully added!"
            }); 

            return RedirectToAction("Index"); 
        } 

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await this.hobie.GetAllHobiesAsync();

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)] 
        public async Task<IActionResult> Remove(int id)
        {
            await this.hobie.RemoveAsync(id); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The hobie is removed!"
            }); 

            return RedirectToAction("Index"); 
        }
    }
}

MyPortfolio/Controllers/MessageController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Infrastructure.Services;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class MessageController : Controller
    {
        private readonly IMessageService message;
        private readonly ICurrentUserService currentUser; 

        public MessageController(
            IMessageService message,
            ICurrentUserService currentUser)
        {
            this.message = message;
            this.currentUser = currentUser;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create() 
        {
            var username = this.currentUser.GetUsername();

            var model = new CreateMessageViewModel
            {
                Username = username,
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateMessageViewModel model)  
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.message.CreateAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Your message was sent successfully. We will contact you!"
            });

            return RedirectToAction("Index", "Home"); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Messages() 
        {
            var model = await this.message.MessagesAsync();

            return this.View(model); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Details(int id)
        {
            var model = await this.message.DetaislsAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Clear(int id)
        {
            await this.message.ClearAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfull!"
            });

            return RedirectToAction("Messages");  
        }
    }
}

MyPortfolio/Controllers/ProjectController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using MyPortfolio.ViewModels.EditViewModel;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class ProjectController : Controller
    {
        private readonly IProjectService project;

        public ProjectController(IProjectService project) => this.project = project; 

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddProjectViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.project.AddAsync(model); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfully added!"
            });

            return RedirectToAction("Index"); 
        } 

        public async Task<IActionResult> Index()
        {
            var model = await this.project.GetAllProjectsAsync(); 

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.project.PrepareForEditingAsync(id); 

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditProjectViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.project.EditAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "This project is edited successfully!"
            });

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> Remove(int id)
        {
            await this.project.RemoveAsync(id); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "This project is removed!"
            }); 

            return RedirectToAction("Index"); 
        }
    }
}

MyPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 

    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Montserrat", sans-serif
        }

        .w3-row-padding img {
            margin-bottom: 12px
        }

        .bgimg {
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-image: url(https://scontent.fsof10-1.fna.fbcdn.net/v/t1.6435-9/238712897_4679668162130046_7453349605803421266_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=zzWnpP1gHSoAX_r9V1N&_nc_ht=scontent.fsof10-1.fna&oh=777be88ab510d1d9b6185a7ae124adf8&oe=614AD414);
            min-height: 100%;
        }
    </style>
</head> 

<body>

    <nav class="w3-sidebar w3-hide-medium w3-hide-small" style="width:40%">
        <div class="bgimg"></div>
    </nav>

    <nav class="w3-sidebar w3-black w3-animate-right w3-xxlarge" style="display:none;padding-top:80px;right:0;z-index:2" id="mySidebar">
        <a href="javascript:void(0)" onclick="closeNav()" class="w3-button w3-black w3-xxxlarge w3-display-topright" style="padding:0 12px;">
            <i class="fa fa-remove"></i>
        </a>
        <div class="w3-bar-block w3-center">
            <a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Home</a>
            <a asp-controller="Project" asp-action="Index" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Portfolio</a>
            <a asp-controller="Experience" asp-action="Index" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Experience</a>
            <a asp-controller="Course" asp-action="Index" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Courses</a>
            <a asp-controller="Education" asp-action="Index" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Education</a>
            <a asp-controller="Hobie" asp-action="Index" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Hobies</a> 
            @if (User.IsInRole("Admin"))
            {
                <a asp-controller="Administration" asp-action="AdministrationUsers" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Administration</a>
            }
        </div>
        <partial name="_LoginPartial" />
    </nav>

    <div class="w3-main w3-padding-large" style="margin-left:40%">

        <span class="w3-button w3-top w3-white w3-xxlarge w3-text-grey w3-hover-text-black" style="width:auto;right:0;" onclick="openNav()"><i class="fa fa-bars"></i></span>

        <header class="w3-container w3-center" style="padding:128px 16px" id="home">
            <h1 class="w3-jumbo"><b>Ivailo Topchiev</b></h1>
            <p><b>Software Engineer</b></p>
            <img src="" class="w3-image w3-hide-large w3-hide-small w3-round" style="display:block;width:60%;margin:auto;">
            <img src="/w3images/profile_girl.jpg" class="w3-image w3-hide-large w3-hide-medium w3-round" width="1000" height="1333">
            <a href="https://cdn.fbsbx.com/v/t59.2708-21/240260571_800567023968061_1317072252943490026_n.pdf/CV.pdf?_nc_cat=104&ccb=1-5&_nc_sid=0cab14&_nc_ohc=E5nhcYHlmTkAX9B17Wc&_nc_ht=cdn.fbsbx.com&oh=0d29c97a3893e84a824a77b8cc4c1097&oe=612D1251&dl=1" download="https://cdn.fbsbx.com/v/t59.2708-21/240260571_800567023968061_1317072252943490026_n.pdf/CV.pdf?_nc_cat=104&ccb=1-5&_nc_sid=0cab14&_nc_ohc=E5nhcYHlmTkAX9B17Wc&_nc_ht=cdn.fbsbx.com&oh=0d29c97a3893e84a824a77b8cc4c1097&oe=612D1251&dl=1" class="w3-button w3-light-grey w3-padding-large w3-margin-top">
                <i class="fa fa-download"></i> Download Resume
            </a>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                <partial name="_MessagePartial" />
                @RenderBody()
            </main>
        </div>
        <!-- Footer -->
        <footer class="w3-container w3-padding-64 w3-light-grey w3-center w3-opacity w3-xlarge">
            <p><b>For Business Proposals</b></p>
            <a asp-controller="Message" asp-action="Create" class="w3-button w3-light-grey w3-padding-large"><i class="fa fa-paper-plane"></i>Message Me</a>
            <br />
            <p><b>Contacts</b></p>
            <p><b><a href="tel:0893690274"><i class="fa fa-fw fa-phone"></i>0893690274</a></b></p>
            <p><b><a href="mailto:ivailotopchiev369@gmail.com"><i class="fa fa-fw fa-envelope"></i>ivailotopchiev369@gmail.com</a></b></p>

            <a href="https://github.com/Ivailo369369"><i class="fa fa-github" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/ivailo.topchiev/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="https://twitter.com/ivailo61472872"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            <a href="https://bg-bg.facebook.com/ivo.topchiev369"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "60%";
            document.getElementById("mySidebar").style.display = "block";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</body>
</html>

MyPortfolio/Views/Shared/_MessagePartial.cshtml
@using MyPortfolio.Infrastructure.Extensions

@if (TempData.ContainsKey("__Message"))
{
    var message = TempData.Get<MessageModel>("__Message"); 
    <message type="@message.Type" message="@message.Message"></message>
} 