MyPortfolio/Controllers/EducationController.cs
namespace MyPortfolio.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyPortfolio.Infrastructure.Extensions;
    using MyPortfolio.Infrastructure.Helpers.Messages;
    using MyPortfolio.Service.Contracts;
    using MyPortfolio.ViewModels.BidingViewModels;
    using MyPortfolio.ViewModels.EditViewModel;
    using System.Threading.Tasks;

    using static Infrastructure.Validation.Administration; 

    public class EducationController : Controller
    {
        private readonly IEducationService education;

        public EducationController(IEducationService education) => this.education = education;

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Add() => this.View();

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Add(AddEducationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.education.AddAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Successfully added!"
            }); 

            return RedirectToAction("Index"); 
        }

        public async Task<IActionResult> Index()
        {
            var model = await this.education.EducationsAsync();

            return View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.education.PrepareForEditingAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditEducationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            await this.education.EditAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The education is edited successfully!"
            });

            return RedirectToAction("Index");
        }
    }
}

MyPortfolio/Views/Education/Add.cshtml
@model MyPortfolio.ViewModels.BidingViewModels.AddEducationViewModel

@{
    ViewData["Title"] = "Add";
}

<h1>Add <b>Education</b></h1> 

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Certificate" class="control-label"></label>
                <input asp-for="Certificate" class="form-control" />
                <span asp-validation-for="Certificate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyPortfolio/Views/Education/Edit.cshtml
@model MyPortfolio.ViewModels.EditViewModel.EditEducationViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData <b>Education</b></h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Certificate" class="control-label"></label>
                <input asp-for="Certificate" class="form-control" />
                <span asp-validation-for="Certificate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyPortfolio/Views/Education/Index.cshtml
@model IEnumerable<MyPortfolio.ViewModels.EducationViewModel.IndexEducationViewModel>

@{
    ViewData["Title"] = "Educations";
}

<style>
    html, body, h1, h2, h3, h4, h5, h6 {
        font-family: "Roboto", sans-serif
    }
</style>

<body>
    <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><b>Education</b></h2>
        <div class="w3-container">
            @foreach (var education in Model)
            {
                <h5 class="w3-opacity"><b>@education.Name</b></h5>
                <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>@education.Start - @education.End</h6>
                <p><b>@education.Description</b></p>
                <a href="@education.Certificate" class="btn btn-outline-info">
                    <p><b>Certificate</b></p>
                </a><hr />
                @if (User.IsInRole("Admin"))
                {
                    <a asp-route-id="@education.Id" asp-controller="Education" asp-action="Edit" class="btn btn-outline-dark"><b>Edit</b></a>
                }
                <hr>
            }
        </div>
    </div>
</body>